version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BBO2022_ROOT_PASSWORD
      MYSQL_DATABASE: BBO2022_DATABASE
      MYSQL_USER: BBO2022_USER
      MYSQL_PASSWORD: BBO2022_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db