worker_processes 1;

events { worker_connections 1024; }

http {

    sendfile on;

    upstream docker-bcoemwebsite {
        server bcoemwebsite:80;
    }

    upstream docker-phpmyadmin {
        server phpmyadmin:80;
    }

    server {
        listen 8080;
        server_name docker-bcoemwebsite;

        location / {
            proxy_pass         http://docker-bcoemwebsite;
            proxy_redirect     off;
            proxy_set_header   Host $http_host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }

        server {
            listen 8081;
            server_name docker-phpmyadmin;

            location / {
                proxy_pass         http://docker-phpmyadmin;
                proxy_redirect     off;
                proxy_set_header   Host $http_host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
            }
        }
}