<?php

declare(strict_types=1);

namespace Bcoem\Domain\LandingPage\Presentation;

final readonly class LandingPageCopy
{
    public function __construct(
        public string $register,
        public string $login,
        public string $logout,
        public string $rules,
        public string $volunteers,
        public string $entryInfo,
        public string $contact,
        public string $sponsors,
        public string $officials,
        public string $results,
        public string $pastWinners,
        public string $upcomingMessage,
        public string $openMessage,
        public string $closedMessage,
        public string $judgeOpenMessage,
        public string $entryLimitMessage,
        public string $nearLimitMessage,
        public string $paidEntryLimitMessage,
        public string $winnerDelayMessage,
        public string $home = 'Home',
        public string $toggleNavigation = 'Toggle navigation',
        public string $account = 'Account',
        public string $hello = 'Hello, %s',
        public string $hostedBy = 'Hosted by',
        public string $atAGlance = 'At a glance',
        public string $entries = 'Entries',
        public string $paidEntries = 'Paid entries',
        public string $entryStatus = 'Entry status',
        public string $dropoffStatus = 'Drop-off status',
        public string $shippingStatus = 'Shipping status',
        public string $statusUpcoming = 'Upcoming',
        public string $statusOpen = 'Open',
        public string $statusClosed = 'Closed',
        public string $shipping = 'Shipping',
        public string $awards = 'Awards',
        public string $awardsTime = 'Awards time',
        public string $registrationDates = 'Account registration',
        public string $entryDates = 'Entry registration',
        public string $judgeDates = 'Judge and steward registration',
        public string $dropoffDates = 'Entry drop-off',
        public string $shippingDates = 'Entry shipping',
        public string $opens = 'Opens',
        public string $closes = 'Closes',
        public string $editAccount = 'Edit account',
        public string $addEntry = 'Add entry',
        public string $registerJudge = 'Register as a judge',
        public string $registerSteward = 'Register as a steward',
        public string $entryAcceptance = 'Entry acceptance',
        public string $dropoffLocations = 'Drop-off locations',
        public string $bestOfShow = 'Best of Show',
        public string $place = 'Place',
        public string $entry = 'Entry',
        public string $brewer = 'Brewer',
        public string $style = 'Style',
        public string $score = 'Score',
        public string $emailAddress = 'Email Address',
        public string $password = 'Password',
        public string $validEmailRequired = 'A valid email is required.',
        public string $passwordRequired = 'Password is required.',
        public string $close = 'Close',
        public string $visitSponsor = 'Visit %s',
    ) {
    }
}
