apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      lokiSearch:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
    isDefault: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
    isDefault: false
